[project]
name = "django-start-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
lint = [
    "ruff>=0.14.10",
]
